library(dplyr)
MechaCar_mpg <- read.csv(file='Data/MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
lm(mpg ~ vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD+mpg,data=MechaCar_mpg)
summary(lm(mpg ~ vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD+mpg,data=MechaCar_mpg))
Suspension_Coil <- read.csv(file='Data/Suspension_Coil.csv',check.names=F,stringsAsFactors = F)
total_summary <- Suspension_Coil %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI)) #create summary table with multiple columns)
lot_summary <- Suspension_Coil %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups='rowwise')
t.test((lot_summary$Mean),mu=mean(total_summary$Mean)) #compare sample versus population means
t.test(subset(lot_summary, Manufacturing_Lot == "Lot1", Mean),(total_summary$Mean))
t.test(subset(lot_summary, Manufacturing_Lot == "Lot2", Mean),(total_summary$Mean))
t.test(subset(lot_summary, Manufacturing_Lot == "Lot3", Mean),(total_summary$Mean))
t.test((lot_1$PSI),mu=mean(total_summary$Mean))
t.test((lot_2$PSI),mu=mean(total_summary$Mean))
t.test((lot_3$PSI),mu=mean(total_summary$Mean))
